FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*"}

[Project]
Name = "TermBuddy"
TargetType = "BeefGUIApplication"
StartupObject = "TermBuddy.Program"

[Platform.Windows]
IconFile = "res/TermBuddy.ico"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib $(LinkFlags)"
BeefLibType = "DynamicDebug"
DebugWorkingDirectory = "c:\\proj\\ClockBuddy"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
OtherLinkFlags = "Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib BeefySysLib64.lib $(LinkFlags)"
BeefLibType = "Dynamic"
